In [28]:
import pandas as pd
df = pd.read_csv("Housing.csv")
df.head()

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [14]:
df.nunique()

price               219
area                284
bedrooms              6
bathrooms             4
stories               4
mainroad              2
guestroom             2
basement              2
hotwaterheating       2
airconditioning       2
parking               4
prefarea              2
furnishingstatus      3
dtype: int64

In [29]:

columns = df.columns[df.nunique() < 10]
for i in range(len(columns)):
    df[columns[i]] = df.groupby([columns[i]])['price'].transform('mean')


df.head()

price  area      bedrooms  ...       parking      prefarea  furnishingstatus
0  13300000  7420  5.729758e+06  ...  5.896328e+06  5.879046e+06      5.495696e+06
1  12250000  8960  5.729758e+06  ...  5.867167e+06  4.425299e+06      5.495696e+06
2  12250000  9960  4.954598e+06  ...  5.896328e+06  5.879046e+06      4.907524e+06
3  12215000  7500  5.729758e+06  ...  5.867167e+06  5.879046e+06      5.495696e+06
4  11410000  7420  5.729758e+06  ...  5.896328e+06  4.425299e+06      5.495696e+06

[5 rows x 13 columns]

In [30]:
x = df.drop(axis=1, columns=['price'])
y = df.price

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(x)
X

array([[0.39656357, 0.9710224 , 0.2489459 , ..., 1.        , 1.        ,
        1.        ],
       [0.5024055 , 0.9710224 , 1.        , ..., 0.98343391, 0.        ,
        1.        ],
       [0.57113402, 0.72155831, 0.2489459 , ..., 1.        , 1.        ,
        0.60308668],
       ...,
       [0.13539519, 0.29592317, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.08659794, 0.72155831, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.15120275, 0.72155831, 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(545, 12))

In [32]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [18]:
lr.coef_

array([3422222.0516495 ,  553548.05959263, 4044819.1086242 ,
       1396716.64494807,  426983.04591843,  284467.24328334,
        362902.88395935,  884067.87484161,  813635.27084503,
        586349.09453748,  644097.84536162,  440824.14931275])

In [9]:
lr.intercept_

np.float64(1594711.9766279939)

In [10]:
lr.tol

1e-06

In [33]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=2)

In [34]:
X_train

array([[0.06597938, 0.72155831, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.42061856, 0.29592317, 0.        , ..., 0.59896911, 0.        ,
        1.        ],
       [0.10549828, 0.29592317, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.15876289, 0.72155831, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.01278351, 0.29592317, 0.        , ..., 0.        , 0.        ,
        0.60308668],
       [0.17938144, 0.9710224 , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(436, 12))

In [35]:
lr.fit(X_train , y_train)

LinearRegression()

In [36]:
lr.coef_

array([3403227.49860019,  419425.5374808 , 3841352.74746107,
       1426701.1188024 ,  378807.59745095,  330532.00469477,
        410709.07019375,  838639.02896196,  823680.94551447,
        581933.63981207,  704916.58645688,  570084.29092406])

In [37]:
y_pred = lr.predict(X_test)

In [38]:
y_pred

array([ 3228360.27196574,  4826696.02657731,  2266048.2503338 ,
        3269395.7139782 ,  6245294.67353361,  4137160.25142196,
        3768111.1241013 ,  2966414.60741719,  4033328.24483441,
        3261812.89549565,  3491927.7389492 ,  3162996.98503216,
        3671197.20219066,  4870830.04074157,  4758487.63920711,
        6940068.42876333,  7190885.24982835,  4587885.52257181,
        2874811.36970301,  4478312.12184815,  5507281.88551384,
        4710870.96280756,  4808684.7100219 ,  6554871.08765685,
        2027471.47723605,  2776078.0160636 ,  2670584.71547176,
        4270466.75630385,  4931741.85324028,  3331837.45083093,
        5004599.33135347,  4241741.71811516,  3905209.00276406,
        4873941.46245912,  4170406.46011512,  7369198.55088658,
        2559072.45490348,  5243399.21552961,  5167955.32798976,
        2712618.51977652,  6926712.91588539,  3212008.34442957,
        3588328.21907471,  4144372.09571999,  2994641.98307053,
        3772391.65653764,  3052534.88371

In [39]:
from sklearn.metrics import mean_absolute_error , mean_squared_error
print(mean_squared_error(y_true=y_test , y_pred=y_pred))
print(mean_absolute_error(y_true=y_test, y_pred=y_pred))

1284541835427.4219
856806.7372229688
